apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    some-annotation: "some-value"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
