apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-update-manifest-yaml-test
  annotations:    
    argo.octopus.com/project: "manifest-deployment"
    argo.octopus.com/environment: "test"
spec:
  project: default
  source:
    repoURL: https://github.com/eddymoulton/octopus-argo-cd-samples
    targetRevision: HEAD
    path: manifests/update-manifests-yaml-octopub/test/
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-update-manifest-yaml-test
  syncPolicy:
    syncOptions:
      - Validate=false
      - CreateNamespace=true
