apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-update-image-tags-yaml-no-sync-test
  annotations:
    argo.octopus.com/project: "argo-step-that-doesn-t-sync"
    argo.octopus.com/environment: "test"
spec:
  project: default
  source:
    repoURL: https://github.com/eddymoulton/octopus-argo-cd-samples
    targetRevision: HEAD
    path: manifests/update-image-tags-yaml-octopub/test-2/
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-update-image-tags-yaml-no-sync-test
  syncPolicy:
    syncOptions:
      - Validate=false
      - CreateNamespace=true
