apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: update-manifests-yaml-multisource-test
  annotations:
    argo.octopus.com/project.yaml-1: "update-manifests-yaml-multisource"
    argo.octopus.com/environment.yaml-1: "test"
    argo.octopus.com/project.yaml-2: "update-manifests-yaml-multisource"
    argo.octopus.com/environment.yaml-2: "test"
spec:
  project: default
  sources:
    - repoURL: https://github.com/eddymoulton/octopus-argo-cd-samples
      targetRevision: HEAD
      path: manifests/update-manifests-yaml-multisource-1/test/
      name: yaml-1
    - repoURL: https://github.com/eddymoulton/octopus-argo-cd-samples
      targetRevision: HEAD
      path: manifests/update-manifests-yaml-multisource-2/test/
      name: yaml-2
  destination:
    server: https://kubernetes.default.svc
    namespace: update-manifests-yaml-multisource-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
