apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: update-image-tags-helm-octopub-default-values-test
  annotations:
    argo.octopus.com/project: "update-image-tags-helm-default-values"
    argo.octopus.com/environment: "test"
    argo.octopus.com/image-replace-paths: "{{ .Values.image.tag}}:{{ .Values.image.version}}"
spec:
  project: default
  source:
    repoURL: https://github.com/eddymoulton/octopus-argo-cd-samples
    targetRevision: HEAD
    path: manifests/update-image-tags-helm-octopub-default-values/test/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: update-manifests-helm-octopub-default-values-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
