apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopub-frontend-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: octopussamples/octopub-frontend:20260228.533.1
          ports:
            - containerPort: 8080
              name: http-port
